### ISSUE TITLE
Compiling with GCC 7 and CLang4,6 fails

### ISSUE THREAD

**Issue by danielstp** [Plaristote/segvcatch#6]
CLANG++-4.0 && 6.0
segvcatch/lib/segvcatch.cpp:89:5: error: member access into incomplete type 'struct ucontext'
    HANDLE_DIVIDE_OVERFLOW;

GCC 7.3.0
segvcatch/lib/x86_64-signal.h:32:26: error: invalid use of incomplete type ‘struct {anonymous}::_Jv_catch_fpe(int, {anonymous}::siginfo_t*, void*)::ucontext’
   gregset_t &_gregs = _uc->uc_mcontext.gregs;

**Comment by Plaristote** [comment]
Thanks for reporting this, it's been fixed in afe79c49f7d.
